### ISSUE TITLE
Health check tests attempt to bind to ports already in use

### ISSUE THREAD

**Issue by AlistairRobinson** [FreddieBrown/stabilize#10]
```
---- backend::tests::test_check_health stdout ----
[Server { quic: V4(127.0.0.1:5347), heartbeat: V4(127.0.0.1:43595) }, Server { quic: V4(127.0.0.1:5348), heartbeat: V4(127.0.0.1:43595) }]
(Stabilize Health) This function will start to check the health of servers in the server pool
(Stabilize Health) Quic: 127.0.0.1:5347, HB: 127.0.0.1:43595
(Stabilize Health) Changing the status of 127.0.0.1:5347
(Stabilize Health) Connected to address: 127.0.0.1:43595
(Stabilize Test) Received: [97]
(Stabilize Health) Received: [98], Server Alive 127.0.0.1:43595
(Stabilize Health) Alive: true
(Stabilize Health) Quic: 127.0.0.1:5348, HB: 127.0.0.1:43595
(Stabilize Health) Changing the status of 127.0.0.1:5348
thread 'backend::tests::test_check_health' panicked at '(Stabilize Health) Couldn't bind socket to address 127.0.0.1:43595: Os { code: 10048, kind: AddrInUse, message: "Only one usage of each socket address (protocol/network address/port) is normally permitted." }', src\backend\mod.rs:152:24

---- backend::tests::test_check_health_runner stdout ----
[Server { quic: V4(127.0.0.1:5347), heartbeat: V4(127.0.0.1:29001) }, Server { quic: V4(127.0.0.1:5348), heartbeat: V4(127.0.0.1:29002) }]
(Stabilize Health) This function will start to check the health of servers in the server pool
(Stabilize Health) Quic: 127.0.0.1:5347, HB: 127.0.0.1:29001
(Stabilize Health) Changing the status of 127.0.0.1:5347
(Stabilize Health) Connected to address: 127.0.0.1:29001
(Stabilize Test) Received: [97]
(Stabilize Health) Received: [98], Server Alive 127.0.0.1:29001
(Stabilize Health) Alive: true
(Stabilize Health) Quic: 127.0.0.1:5348, HB: 127.0.0.1:29002
(Stabilize Health) Changing the status of 127.0.0.1:5348
thread 'backend::tests::test_check_health_runner' panicked at '(Stabilize Health) Couldn't bind socket to address 127.0.0.1:29002: Os { code: 10048, kind: AddrInUse, message: "Only one usage of each socket address (protocol/network address/port) is normally permitted." }', src\backend\mod.rs:152:24
thread 'backend::tests::test_check_health_runner' panicked at 'assertion failed: `(left == right)`
  left: `true`,
 right: `false`', src\backend\tests.rs:126:5
```

This is the output of tests `test_check_health` and `test_check_health_runner` when run on a machine using Windows 10. I have verified that none of these ports are being used by other applications on the system using `netstat`. Are ports potentially being assigned to multiple actors at once?

**Comment by FreddieBrown** [comment]
This is an issue on Windows 10 but is out of scope for this project.
